server {
    listen 80;
    server_name _;

    location /my-tunnel {
        proxy_pass https://musical-spoon-qvq594gq54qv3x6x7-443.app.github.dev/my-tunnel;
        proxy_set_header Host musical-spoon-qvq594gq54qv3x6x7-443.app.github.dev;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_ssl_server_name on;
        proxy_ssl_verify off;
    }
}
